[2023-10-26T10:34:03.816+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_db_and_save_local.read_db scheduled__2023-10-24T00:00:00+00:00 [queued]>
[2023-10-26T10:34:03.825+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_db_and_save_local.read_db scheduled__2023-10-24T00:00:00+00:00 [queued]>
[2023-10-26T10:34:03.826+0000] {taskinstance.py:1359} INFO - Starting attempt 4 of 4
[2023-10-26T10:34:03.837+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): read_db> on 2023-10-24 00:00:00+00:00
[2023-10-26T10:34:03.842+0000] {standard_task_runner.py:57} INFO - Started process 549 to run task
[2023-10-26T10:34:03.845+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'read_db_and_save_local', 'read_db', 'scheduled__2023-10-24T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/read_db_and_save_local.py', '--cfg-path', '/tmp/tmphdlrgb4g']
[2023-10-26T10:34:03.847+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask read_db
[2023-10-26T10:34:03.896+0000] {task_command.py:415} INFO - Running <TaskInstance: read_db_and_save_local.read_db scheduled__2023-10-24T00:00:00+00:00 [running]> on host 88a410f69adf
[2023-10-26T10:34:04.151+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_db_and_save_local' AIRFLOW_CTX_TASK_ID='read_db' AIRFLOW_CTX_EXECUTION_DATE='2023-10-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-24T00:00:00+00:00'
[2023-10-26T10:34:04.158+0000] {base.py:73} INFO - Using connection ID 'mydb' for task execution.
[2023-10-26T10:34:04.167+0000] {logging_mixin.py:151} INFO - (('Danasawin', '19'),)
[2023-10-26T10:34:04.168+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-26T10:34:04.176+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=read_db_and_save_local, task_id=read_db, execution_date=20231024T000000, start_date=20231026T103403, end_date=20231026T103404
[2023-10-26T10:34:04.218+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-26T10:34:04.232+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
